// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0u0otABSGUNpOB8OahLbyKBlehFzTSgo',
    appId: '1:398786405206:web:8e7f690c5f45bee3b0acf7',
    messagingSenderId: '398786405206',
    projectId: 'news-2e342',
    authDomain: 'news-2e342.firebaseapp.com',
    storageBucket: 'news-2e342.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkqUUIgzU6ano7H_C-Z_sLqcpD_lqHe8k',
    appId: '1:398786405206:android:235d09d2a3a1c477b0acf7',
    messagingSenderId: '398786405206',
    projectId: 'news-2e342',
    storageBucket: 'news-2e342.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKh5MAzmIGPbhNyn2OvvARidWsjTq-iNE',
    appId: '1:398786405206:ios:d59f2b543dc6aaa5b0acf7',
    messagingSenderId: '398786405206',
    projectId: 'news-2e342',
    storageBucket: 'news-2e342.appspot.com',
    iosBundleId: 'com.example.news',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKh5MAzmIGPbhNyn2OvvARidWsjTq-iNE',
    appId: '1:398786405206:ios:bdcf7ccd56edd1e0b0acf7',
    messagingSenderId: '398786405206',
    projectId: 'news-2e342',
    storageBucket: 'news-2e342.appspot.com',
    iosBundleId: 'com.example.news.RunnerTests',
  );
}
